package fr.sgr.formation.voteapp.traces.modele;

public enum TypeAction {
	USR_CREATION,
	USR_CONSULT,
	USR_RENOUVMDP,
	USR_MODIF,
	USR_LISTE,
	TR_CONSULT,
	ELEC_CREATION,
	ELEC_CLOTURE,
	ELEC_MODIF,
	ELEC_CONSULT,
	ELEC_RECHERCHE,
	ELEC_LISTE,
	VOTE;
}
